/*
 * This source file was generated by the Gradle 'init' task
 */
package com.example.Sample;

public class App {
   

    public static void main(String[] args) {
        Car c1=new Car(4,"TaTa",120);
        System.out.println("information"+"\n"+"Speed Limit:"+c1.speed+"\n"+"Brand Name:"+c1.brand+"\n"+"Total Numbers of Doors:"+c1.doors);
        
        Bike b1=new Bike(true,"KTM",180);
        System.out.println("Informations"+"\n"+"Bike has carrier:"+b1.hasCarrier+"\n"+"Brand Name:"+b1.brand+"\n"+"Speed Limit:"+b1.speed);
        
        Bus bus=new Bus(50,"Sleeper","Shivashahi",95);
        System.out.println("Information"+"\n"+"Total Capacity:"+bus.passengersCapacity+"\n"+"Bus Type:"+bus.type+"\n"+"Brand :"+bus.brand+"\n"+"Speed Limit:"+bus.speed);
    }
}
